---
- name: create databases
  mysql_db:
    name: "{{ item.name }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
  loop: "{{ databases|default([]) }}"

- name: create users
  mysql_user:
    name: "{{ item.name }}"
    host: "{{ item.host | default('localhost') }}"
    password: "{{ item.password }}"
    priv: "{{ item.priv|default(item.name ~ '.*:ALL') }}"
  loop: "{{ users|default([]) }}"
