---
- name: create service dir
  file:
    path: "/etc/systemd/system/{{ mysql_versions[version].systemd_unit_override_dir }}"
    state: directory
    mode: 0755

- name: place override.conf
  template:
    src: systemd-override.j2
    dest: "/etc/systemd/system/{{ mysql_versions[version].systemd_unit_override_dir }}/override.conf"
    owner: root
    group: root
    mode: 0644
  notify: reload mysql unit

- name: create directory {{ templates_dir }}/mysql
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0755
  loop:
    - "{{ templates_dir }}/mysql"
    - "{{ templates_dir }}/profiles"

- name: include deploy-functions
  include_role:
    name: deploy-functions
  when: deploy_functions_installed is not defined

- name: place inital-setup script
  template:
    src: "{{ initial_setup_template }}"
    dest: "{{ templates_dir }}/mysql/initial-setup"
    owner: "root"
    group: "root"
    mode: 0750
