---
- name: set a root password
  mysql_user:
    user: root
    password: "{{ root_password }}"
    host_all: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when: ansible_distribution_release == 'focal'

- name: set a root password
  mysql_user:
    user: root
    password: "{{ root_password }}"
    host_all: yes
  when: ansible_distribution_release != 'focal'

- name: create .my.cnf file
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    mode: 0600

- name: create lxhelper profile placeholders (workaround for initial_setup enabled)
  template:
    src: lxhelper_profile.j2
    dest: "{{ item }}"
    mode: 0600
  when: initial_setup
  loop:
    - "{{ templates_dir }}/profiles/default.yml"
    - "{{ templates_dir }}/profiles/current.yml"
